### ISSUE TITLE
Ressources icons also shown on other (completely unrelated) maps

### ISSUE THREAD

**Issue by Ghostwalker83** [reyzor1991/pf2e-kingmaker-helper#1]
I noticed that the ressources icons also appear on the majority of other battlemaps (not all other maps apparently, but I haven't been able to figure out a scheme behind it, but the vast majority of maps included in the official module, including the Landing Page, are affected) when "Show colored hexes" is toggled on. Switching back to the Stolen Lands map and toggling the option off resolves the display issue.

**Comment by reyzor1991** [comment]
I will try to fix it ASAP

**Comment by Ghostwalker83** [comment]
Awesome, thanks a lot for the quick response. Seems to be working just fine now. Much appreciated!
